name: "Check Author Lockfile"

on:
  workflow_call:
    inputs:
      runs_on:
        required: false
        type: string
        default: self-hosted

      lockfile_author:
        required: true
        type: string
        default: 'none'
      
      action:
        required: true
        type: string

jobs:
  check_author_lockfile:
    name: Check Author Lockfile
    runs-on: ${{ inputs.runs_on }}
    steps:
      - name: No canary deployment yet
        if: ${{ inputs.lockfile_author == 'none' }}
        run: |
          echo "# There isn't any new canary deployment" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## Please create a new canary deployment before doing a promote or abort." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Additional info:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- lockfile_author: ${{ inputs.lockfile_author }}" >> $GITHUB_STEP_SUMMARY
          echo "- triggering_actor: ${{ github.triggering_actor }}" >> $GITHUB_STEP_SUMMARY
          echo "- selected_action: ${{ inputs.action }}" >> $GITHUB_STEP_SUMMARY
          exit 1


      - name: Triggering actor mismatch
        if: ${{ ( inputs.lockfile_author != 'none' ) && ( inputs.lockfile_author != github.triggering_actor ) }}
        run: |
          echo "# Triggering actor mismatch" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## The one who promote or abort current canary deployment must be the one who is originally initiated it." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## Contact the one who initiate it, or edit the lockfile in case they aren't able to do it." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Additional info:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- lockfile_author: ${{ inputs.lockfile_author }}" >> $GITHUB_STEP_SUMMARY
          echo "- triggering_actor: ${{ github.triggering_actor }}" >> $GITHUB_STEP_SUMMARY
          echo "- selected_action: ${{ inputs.action }}" >> $GITHUB_STEP_SUMMARY
          exit 1

      - name: Deployment unfinidhed
        if: ${{ ( inputs.lockfile_author != 'none' ) && ( inputs.lockfile_author == github.triggering_actor ) }}
        run: |
          echo "# Previous deployment is not finished yet!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## Please complete the deployment by either finish the promote step or abort the current deployment." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Additional info:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- lockfile_author: ${{ inputs.lockfile_author }}" >> $GITHUB_STEP_SUMMARY
          echo "- triggering_actor: ${{ github.triggering_actor }}" >> $GITHUB_STEP_SUMMARY
          echo "- selected_action: ${{ inputs.action }}" >> $GITHUB_STEP_SUMMARY
          exit 1
