name: "Create Lockfile"

on:
  workflow_call:
    inputs:
      runs_on:
        required: false
        type: string
        default: self-hosted

      environment:
        required: true
        type: string

      service_name:
        required: false
        type: string
        default: "ltms-demo"

      repository:
        required: false
        type: string
        default: kargotech/rhodes

      argocd_directory:
        required: true
        type: string
      
      lockfile_directory:
        required: false
        type: string
        default: none

      lockfile_name:
        required: false
        type: string
        default: none

    secrets:
      deployer_app_id:
        required: true
      deployer_private_key:
        required: true
      deployer_installation_id:
        required: true

jobs:
  create_lockfile:
    name: Create lockfile
    runs-on: ${{ inputs.runs_on }}
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.deployer_app_id }}
          private_key: ${{ secrets.deployer_private_key }}
          installation_id: ${{ secrets.deployer_installation_id }}
          repository: ${{ inputs.repository }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout deployment repo
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository }}
          token: ${{ steps.generate_token.outputs.token }}
          path: temp
      
      - name: Set git config
        run: |
          AUTHOR_NAME=$(git show -s --format='%aN' ${{ github.sha }})
          AUTHOR_EMAIL=$(git show -s --format='%ae' ${{ github.sha }})
          git config --global user.name "${AUTHOR_NAME}"
          git config --global user.email "${AUTHOR_EMAIL}"

      - name: Commit lockfile
        uses: nick-invision/retry@v2
        with:
          timeout_seconds: 15
          max_attempts: 6
          command: |
            if [ ${{ inputs.lockfile_directory }} == "none" ]
            then
              LOCKFILEDIR=temp/${{ inputs.argocd_directory }}
              LOCKFILENAME="${{ inputs.environment }}-${{ inputs.service_name }}.lock"
            else
              LOCKFILEDIR=temp/${{ inputs.lockfile_directory }}
              LOCKFILENAME=${{ inputs.lockfile_name }}
            fi
            cd $LOCKFILEDIR
            git fetch origin master
            git reset --hard origin/master
            echo "lockfile_author=${{ github.triggering_actor }}" > $LOCKFILENAME
            echo "timestamp=$(date +'%s')" >> $LOCKFILENAME
            echo "commit_sha=${{ github.sha }}" >> $LOCKFILENAME
            echo "service_name=${{ inputs.service_name }}" >> $LOCKFILENAME
            echo "environment=${{ inputs.environment }}" >> $LOCKFILENAME
            cat $LOCKFILENAME
            git add $LOCKFILENAME
            git commit -am "Update lockfile for '${{ inputs.service_name }}' '${{ inputs.environment }}'"
            git push
