name: "Deployment"

on:
  workflow_call:
    inputs:
      runs_on:
        required: false
        type: string
        default: self-hosted

      environment:
        required: true
        type: string

      service_name:
        required: false
        type: string
        default: "ltms-demo"

      repository:
        required: false
        type: string
        default: kargotech/rhodes

      gcp_project_id:
        required: false
        type: string
        default: kargotech-prod

      gke_cluster:
        required: false
        type: string
        default: helios

      gke_zone:
        required: false
        type: string
        default: asia-southeast2-a

      argocd_directory:
        required: true
        type: string

      argocd_values_file:
        required: false
        type: string
        default: "values.yaml"

      argocd_app:
        required: true
        type: string

      argocd_version:
        required: false
        type: string
        default: "2.5.2"

      argocd_timeout:
        required: false
        type: number
        default: 600

      is_canary:
        required: false
        type: boolean
        default: false

      use_argo_sync:
        required: false
        type: boolean
        default: true

      pushgateway_url:
        required: false
        type: string
        default: https://prometheus-root-pushgateway.monitor.svc.cluster.local:9091

    secrets:
      deployer_app_id:
        required: true
      deployer_private_key:
        required: true
      deployer_installation_id:
        required: true

jobs:
  deployment:
    name: Deploy
    runs-on: ${{ inputs.runs_on }}
    environment: ${{ inputs.environment }}

    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.deployer_app_id }}
          private_key: ${{ secrets.deployer_private_key }}
          installation_id: ${{ secrets.deployer_installation_id }}
          repository: ${{ inputs.repository }}

      - name: Checkout code
        uses: actions/checkout@v3
      - name: Checkout deployment repo
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository }}
          token: ${{ steps.generate_token.outputs.token }}
          path: temp

      - name: Set git config
        run: |
          AUTHOR_NAME=$(git show -s --format='%aN' ${{ github.sha }})
          AUTHOR_EMAIL=$(git show -s --format='%ae' ${{ github.sha }})
          git config --global user.name "${AUTHOR_NAME}"
          git config --global user.email "${AUTHOR_EMAIL}"
      - name: Update service tag
        uses: nick-invision/retry@v2
        with:
          timeout_seconds: 15
          max_attempts: 6
          command: |
            cd temp/${{ inputs.argocd_directory }}
            git fetch origin master
            git reset --hard origin/master
            sed '/app:/,/^[a-zA-Z]/ { s/^    tag: .*/    tag: "'${{ github.sha }}'"/g }' ${{ inputs.argocd_values_file }} > temp && mv temp ${{ inputs.argocd_values_file }}
            sed '/app:/,/^[a-zA-Z]/ { s/^    app-version: .*/    app-version: "'${{ github.ref_name }}'"/g }' ${{ inputs.argocd_values_file }} > temp && mv temp ${{ inputs.argocd_values_file }}
            git commit -am "Bumped ${{ inputs.service_name }} service in '${{ inputs.environment }}' to tag '${{ github.sha }}'"
            git push

      # Setup gcloud CLI
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        if: ${{ inputs.use_argo_sync }}
        with:
          install_components: kubectl

      - name: Setup Kubernetes config
        if: ${{ inputs.use_argo_sync }}
        run: |
          gcloud container clusters get-credentials "${{ inputs.gke_cluster }}" --zone "${{ inputs.gke_zone }}"
          kubectl config set-context --current --namespace=argocd

      - name: ArgoCD sync app
        uses: clowdhaus/argo-cd-action/@v1.15.0
        if: ${{ inputs.use_argo_sync }}
        with:
          version: ${{ inputs.argocd_version }}
          command: app sync ${{ inputs.argocd_app }}
          options: --core --async

      - name: ArgoCD wait until application healthy (non canary)
        id: wait_deployment
        uses: clowdhaus/argo-cd-action/@v1.15.0
        if: ${{ ( inputs.is_canary == false ) && ( inputs.use_argo_sync ) }}
        with:
          version: ${{ inputs.argocd_version }}
          command: app wait ${{ inputs.argocd_app }}
          options: --core --timeout ${{ inputs.argocd_timeout }}

      - name: ArgoCD wait until application healthy (canary)
        id: wait_deployment_canary
        uses: clowdhaus/argo-cd-action/@v1.15.0
        if: ${{ ( inputs.is_canary ) && ( inputs.use_argo_sync ) }}
        with:
          version: ${{ inputs.argocd_version }}
          command: app wait ${{ inputs.argocd_app }}
          options: --core --suspended --timeout ${{ inputs.argocd_timeout }}

      - name: Publish metrics to Prometheus Gateway
        if: always()
        run: |
          APP_LABELS="environment/${{ env.environment }}/app/${{ env.service_name }}/is_canary/${{ env.is_canary }}/result_canary/${{ steps.wait_deployment_canary.outcome }}/result_non_canary/${{ steps.wait_deployment.outcome }}"

          RUNNER_LABELS="run_id/$GITHUB_RUN_ID/run_attempt/$GITHUB_RUN_ATTEMPT"

          echo "github_action_deployment_event 1" | \
            curl -XPUT --binary-data @- ${{ env.pushgateway_url }}/metrics/job/deployment/$APP_LABELS/$RUNNER_LABELS
