name: "Rollout Canary"

on:
  workflow_call:
    inputs:
      runs_on:
        required: false
        type: string
        default: self-hosted

      environment:
        required: true
        type: string

      service_name:
        required: false
        type: string
        default: "ltms-demo"

      repository:
        required: false
        type: string
        default: kargotech/rhodes

      gcp_project_id:
        required: false
        type: string
        default: kargotech-prod

      gke_cluster:
        required: false
        type: string
        default: helios

      gke_zone:
        required: false
        type: string
        default: asia-southeast2-a

      argocd_directory:
        required: true
        type: string

      argocd_values_file:
        required: false
        type: string
        default: "values.yaml"

      argocd_app:
        required: true
        type: string

      argocd_version:
        required: false
        type: string
        default: "2.5.2"
      
      argocd_timeout:
        required: false
        type: number
        default: 600
      
      argocd_wait_for:
        required: false
        type: string
        default: suspended
      
      argo_rollout_command:
        required: false
        type: string
        default: 'none'
      
      http_routes:
        required: true
        type: string
        default: 'none'
      
      release:
        required: true
        type: string
        default: 'none'
      
      with_notification:
        required: false
        type: boolean
        default: false

      other_mentions:
        required: false
        type: string
        default: ''

    secrets:
      deployer_app_id:
        required: true
      deployer_private_key:
        required: true
      deployer_installation_id:
        required: true
      webhook_url:
        required: false

jobs:
  argo_rollout_and_change_release_track:
    name: Argo Rollout and Change Release Track
    runs-on: ${{ inputs.runs_on }}    
    steps:
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          install_components: kubectl

      - name: Setup Kubernetes config
        run: |
          gcloud container clusters get-credentials "${{ inputs.gke_cluster }}" --zone "${{ inputs.gke_zone }}"
          kubectl config set-context --current --namespace=argocd

      - name: ArgoCD run Argo Rollout action
        uses: clowdhaus/argo-cd-action/@v1.15.0
        if: ${{ inputs.argo_rollout_command != 'none' }} 
        with:
          version: ${{ inputs.argocd_version }}
          command: app actions run ${{ inputs.argocd_app }} ${{ inputs.argo_rollout_command }}
          options: --core --kind Rollout

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        if: ${{ (inputs.http_routes != 'none') && (inputs.release != 'none') }}
        with:
          app_id: ${{ secrets.deployer_app_id }}
          private_key: ${{ secrets.deployer_private_key }}
          installation_id: ${{ secrets.deployer_installation_id }}
          repository: ${{ inputs.repository }}
      
      - name: Checkout code
        uses: actions/checkout@v3
        if: ${{ (inputs.http_routes != 'none') && (inputs.release != 'none') }}

      - name: Checkout deployment repo
        uses: actions/checkout@v3
        if: ${{ (inputs.http_routes != 'none') && (inputs.release != 'none') }}
        with:
          repository: ${{ inputs.repository }}
          token: ${{ steps.generate_token.outputs.token }}
          path: temp

      - name: Set git config
        if: ${{ (inputs.http_routes != 'none') && (inputs.release != 'none') }}
        run: |
          AUTHOR_NAME=$(git show -s --format='%aN' ${{ github.sha }})
          AUTHOR_EMAIL=$(git show -s --format='%ae' ${{ github.sha }})
          NOTIFICATION_EMAILS=${AUTHOR_EMAIL},${{ inputs.other_mentions }}
          echo "notification_emails=$NOTIFICATION_EMAILS" >> $GITHUB_ENV
          git config --global user.name "${AUTHOR_NAME}"
          git config --global user.email "${AUTHOR_EMAIL}"

      - name: Update routes release
        uses: nick-invision/retry@v2
        if: ${{ (inputs.http_routes != 'none') && (inputs.release != 'none') }}
        with:
          timeout_seconds: 15
          max_attempts: 6
          shell: bash
          command: |
            cd temp/${{ inputs.argocd_directory }}
            git fetch origin master
            git reset --hard origin/master
            array=( ${{ inputs.http_routes }} )
            for route in "${array[@]}"
            do
              sed -e "/$route/!b" -e ':a' -e "s/^              subset: .*/              subset: ${{ inputs.release }}/;t trail" -e 'n;ba' -e ':trail' -e 'n;btrail' ${{ inputs.argocd_values_file }} > temp && mv temp ${{ inputs.argocd_values_file }}
            done
            git commit -am "Change '${{ inputs.http_routes }}' to '${{ inputs.release }}' release for '${{ inputs.service_name }}' '${{ inputs.environment }}'"
            git push

      - name: ArgoCD sync app
        uses: clowdhaus/argo-cd-action/@v1.15.0
        with:
          version: ${{ inputs.argocd_version }}
          command: app sync ${{ inputs.argocd_app }}
          options: --core --async --timeout ${{ inputs.argocd_timeout }}
      
      - name: ArgoCD wait until application healthy (canary)
        uses: clowdhaus/argo-cd-action/@v1.15.0
        with:
          version: ${{ inputs.argocd_version }}
          command: app wait ${{ inputs.argocd_app }}
          options: --core --${{ inputs.argocd_wait_for }} --timeout ${{ inputs.argocd_timeout }}

      - name: Failed notification
        if: ${{ failure() && inputs.with_notification }}
        uses: kargotech/msteams-webhook-action/@v0.1.2
        with:
          webhook_url: ${{ secrets.webhook_url }}
          status: failed
          title: Change ${{ inputs.http_routes }} to ${{ inputs.release }} release for ${{ inputs.service_name }} ${{ inputs.environment }} failed
          description: ArgoCD command - ${{ inputs.argo_rollout_command }}. Check via link below for more info.
          mentioned_display: ${{ env.notification_emails }}
          mentioned_email: ${{ env.notification_emails }}
          link_display: Workflow Result
          link_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      
      - name: Success notification
        if: ${{ success() && inputs.with_notification }}
        uses: kargotech/msteams-webhook-action/@v0.1.2
        with:
          webhook_url: ${{ secrets.webhook_url }}
          status: success
          title: Change ${{ inputs.http_routes }} to ${{ inputs.release }} release for ${{ inputs.service_name }} ${{ inputs.environment }} success
          description: ArgoCD command - ${{ inputs.argo_rollout_command }}. Check via link below for more info.
          mentioned_display: ${{ env.notification_emails }}
          mentioned_email: ${{ env.notification_emails }}
          link_display: Workflow Result
          link_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Annotate Canary Rollout to Grafana
        uses: frankie567/grafana-annotation-action@v1.0.2
        with:
          apiHost: ${{ secrets.GRAFANA_API_URL }}
          apiToken: ${{ secrets.GRAFANA_API_TOKEN }}
          text: Canary Rollout with http routes (${{ inputs.http_routes }}) of ${{ github.sha }}
          tags: event:canary-rollout,service:${{ inputs.service-name }}
