name: "Rollout Canary"

on:
  workflow_call:
    inputs:
      runs_on:
        required: false
        type: string
        default: self-hosted

      environment:
        required: true
        type: string

      service_name:
        required: false
        type: string
        default: "ltms-demo"

      repository:
        required: false
        type: string
        default: kargotech/rhodes

      gcp_project_id:
        required: false
        type: string
        default: kargotech-prod

      gke_cluster:
        required: false
        type: string
        default: helios

      gke_zone:
        required: false
        type: string
        default: asia-southeast2-a

      argocd_directory:
        required: true
        type: string

      argocd_values_file:
        required: false
        type: string
        default: "values.yaml"

      argocd_app:
        required: true
        type: string

      argocd_version:
        required: false
        type: string
        default: "2.4.11"
      
      argocd_timeout:
        required: false
        type: number
        default: 600
      
      argo_rollout_command:
        required: false
        type: string
        default: 'none'
      
      http_routes:
        required: true
        type: string
      
      release:
        required: true
        type: string

    secrets:
      deployer_app_id:
        required: true
      deployer_private_key:
        required: true
      deployer_installation_id:
        required: true

jobs:
  argo_rollout:
    name: Argo Rollout
    runs-on: ${{ inputs.runs_on }}
    if: ${{ inputs.argo_rollout_command != 'none' }} 
    steps:
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v0
        with:
          install_components: kubectl

      - name: Setup Kubernetes config
        run: |
          gcloud container clusters get-credentials "${{ inputs.gke_cluster }}" --zone "${{ inputs.gke_zone }}"
          kubectl config set-context --current --namespace=argocd

      - name: ArgoCD run Argo Rollout action
        uses: clowdhaus/argo-cd-action/@main
        with:
          version: ${{ inputs.argocd_version }}
          command: app actions run ${{ inputs.argocd_app }} ${{ inputs.argo_rollout_command }}
          options: --core --kind Rollout

  change_release:
    name: Change release
    runs-on: ${{ inputs.runs_on }}
    needs: argo_rollout
    if: ${{ always() }}
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.deployer_app_id }}
          private_key: ${{ secrets.deployer_private_key }}
          installation_id: ${{ secrets.deployer_installation_id }}
          repository: ${{ inputs.repository }}
      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout deployment repo
        uses: actions/checkout@v2
        with:
          repository: ${{ inputs.repository }}
          token: ${{ steps.generate_token.outputs.token }}
          path: temp

      - name: Set git config
        run: |
          AUTHOR_NAME=$(git show -s --format='%aN' ${{ github.sha }})
          AUTHOR_EMAIL=$(git show -s --format='%ae' ${{ github.sha }})
          git config --global user.name "${AUTHOR_NAME}"
          git config --global user.email "${AUTHOR_EMAIL}"

      - name: Update routes release
        uses: nick-invision/retry@v2
        with:
          timeout_seconds: 15
          max_attempts: 6
          shell: bash
          command: |
            cd temp/${{ inputs.argocd_directory }}
            git fetch origin master
            git reset --hard origin/master
            array=( ${{ inputs.http_routes }} )
            for route in "${array[@]}"
            do
              sed -e "/$route/!b" -e ':a' -e "s/^              subset: .*/              subset: ${{ inputs.release }}/;t trail" -e 'n;ba' -e ':trail' -e 'n;btrail' ${{ inputs.argocd_values_file }} > temp && mv temp ${{ inputs.argocd_values_file }}
            done
            git commit -am "Change '${{ inputs.http_routes }}' to '${{ inputs.release }}' release for '${{ inputs.service_name }}' '${{ inputs.environment }}'"
            git push

      - name: ArgoCD sync app
        uses: clowdhaus/argo-cd-action/@main
        with:
          version: ${{ inputs.argocd_version }}
          command: app sync ${{ inputs.argocd_app }}
          options: --core --async
